--- #YAML:1.0
name:               Pod-Perldoc
version:            3.15_11
abstract:           Look up Perl documentation in Pod format.
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config:               0
    Fcntl:                0
    File::Spec::Functions:  0
    File::Temp:           0.22
    parent:               0
    Pod::Man:             2.18
    Pod::Simple::RTF:     3.16
    Pod::Simple::XMLOutStream:  3.16
    Pod::Text:            0
    strict:               0
    Symbol:               0
    Test::More:           0
    Text::ParseWords:     0
    warnings:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
