--- #YAML:1.0
name:                Pod-Perldoc
version:             3.14_03
abstract:            look up Perl documentation in Pod format
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Config:                        0
    Fcntl:                         0
    File::Spec::Functions:         0
    File::Temp:                    0
    strict:                        0
    Symbol:                        0
    Text::ParseWords:              0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
