--- #YAML:1.0
name:               Pod-Perldoc
version:            3.15_01
abstract:           Look up Perl documentation in Pod format.
author:
    - Adriano R. Ferreira <ferreira@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config:               0
    Fcntl:                0
    File::Spec::Functions:  0
    File::Temp:           0
    strict:               0
    Symbol:               0
    Text::ParseWords:     0
    warnings:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
