--- #YAML:1.0
name:                Pod-Perldoc
version:             3.14_07
abstract:            Look up Perl documentation in Pod format.
license:             perl
author:              
    - Adriano R. Ferreira <ferreira@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config:                        0
    Fcntl:                         0
    File::Spec::Functions:         0
    File::Temp:                    0
    strict:                        0
    Symbol:                        0
    Text::ParseWords:              0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
