# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-Perldoc
version:      3.11
version_from: lib/Pod/Perldoc.pm
installdirs:  site
requires:
    Config:                        0
    Fcntl:                         0
    File::Spec::Functions:         0
    File::Temp:                    0
    strict:                        0
    Symbol:                        0
    Text::ParseWords:              0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
